// Generated by jbindgen. DO NOT EDIT.

#[allow(unused_imports)]
use jni::objects::{
    JClass, JFieldID, JMethodID, JObject, JStaticFieldID, JString, JThrowable, JValue,
};
#[allow(unused_imports)]
use jni::sys::*;
use jni::JNIEnv;

#[allow(non_snake_case)]
#[no_mangle]
fn Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeEnclaveStart<'a>(
    arg1: JNIEnv,
    arg2: JClass<'a>,
    arg3: JString<'a>,
    arg4: jboolean,
    arg5: jbyte,
    arg6: JObject<'a>,
) {
    return crate :: jniimpl :: Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeEnclaveStart ( arg1 , arg2 , arg3 , arg4 , arg5 , arg6 );
}

#[allow(non_snake_case)]
#[no_mangle]
fn Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeGetNextQuote<'a>(
    arg1: JNIEnv,
    arg2: JClass<'a>,
    arg3: jlong,
    arg4: jbyteArray,
    arg5: jbyteArray,
) -> jbyteArray {
    return crate :: jniimpl :: Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeGetNextQuote ( arg1 , arg2 , arg3 , arg4 , arg5 );
}

#[allow(non_snake_case)]
#[no_mangle]
fn Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeSetCurrentQuote<'a>(
    arg1: JNIEnv,
    arg2: JClass<'a>,
    arg3: jlong,
) {
    return crate :: jniimpl :: Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeSetCurrentQuote ( arg1 , arg2 , arg3 );
}

#[allow(non_snake_case)]
#[no_mangle]
fn Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeNegotiateRequest<'a>(
    arg1: JNIEnv,
    arg2: JClass<'a>,
    arg3: jlong,
    arg4: jbyteArray,
) -> jobject {
    return crate :: jniimpl :: Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeNegotiateRequest ( arg1 , arg2 , arg3 , arg4 );
}

#[allow(non_snake_case)]
#[no_mangle]
fn Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeServerStart<'a>(
    arg1: JNIEnv,
    arg2: JClass<'a>,
    arg3: jlong,
    arg4: jlong,
    arg5: jint,
) {
    return crate :: jniimpl :: Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeServerStart ( arg1 , arg2 , arg3 , arg4 , arg5 );
}

#[allow(non_snake_case)]
#[no_mangle]
fn Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeServerCall<'a>(
    arg1: JNIEnv,
    arg2: JClass<'a>,
    arg3: jlong,
    arg4: jlong,
    arg5: JObject<'a>,
    arg6: JObject<'a>,
) {
    return crate :: jniimpl :: Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeServerCall ( arg1 , arg2 , arg3 , arg4 , arg5 , arg6 );
}

#[allow(non_snake_case)]
#[no_mangle]
fn Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeServerStop<'a>(
    arg1: JNIEnv,
    arg2: JClass<'a>,
    arg3: jlong,
    arg4: jlong,
    arg5: JObject<'a>,
    arg6: JObject<'a>,
    arg7: jlong,
) {
    return crate :: jniimpl :: Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeServerStop ( arg1 , arg2 , arg3 , arg4 , arg5 , arg6 , arg7 );
}

#[allow(non_snake_case)]
#[no_mangle]
fn Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeReportPlatformAttestationStatus<
    'a,
>(
    arg1: JNIEnv,
    arg2: JClass<'a>,
    arg3: jbyteArray,
    arg4: jboolean,
) -> jint {
    return crate :: jniimpl :: Java_org_whispersystems_contactdiscovery_enclave_SgxEnclave_nativeReportPlatformAttestationStatus ( arg1 , arg2 , arg3 , arg4 );
}
