/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_whispersystems_contactdiscovery_directory_DirectoryMapNative */

#ifndef _Included_org_whispersystems_contactdiscovery_directory_DirectoryMapNative
#define _Included_org_whispersystems_contactdiscovery_directory_DirectoryMapNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_whispersystems_contactdiscovery_directory_DirectoryMapNative
 * Method:    nativeInit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_whispersystems_contactdiscovery_directory_DirectoryMapNative_nativeInit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_whispersystems_contactdiscovery_directory_DirectoryMapNative
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_whispersystems_contactdiscovery_directory_DirectoryMapNative_nativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_whispersystems_contactdiscovery_directory_DirectoryMapNative
 * Method:    nativeInsert
 * Signature: (JJLjava/util/UUID;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_whispersystems_contactdiscovery_directory_DirectoryMapNative_nativeInsert
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_whispersystems_contactdiscovery_directory_DirectoryMapNative
 * Method:    nativeRemove
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_whispersystems_contactdiscovery_directory_DirectoryMapNative_nativeRemove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_whispersystems_contactdiscovery_directory_DirectoryMapNative
 * Method:    nativeBorrow
 * Signature: (JLorg/whispersystems/contactdiscovery/directory/DirectoryMapNative/BorrowFunction;)V
 */
JNIEXPORT void JNICALL Java_org_whispersystems_contactdiscovery_directory_DirectoryMapNative_nativeBorrow
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_whispersystems_contactdiscovery_directory_DirectoryMapNative
 * Method:    nativeCommit
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_whispersystems_contactdiscovery_directory_DirectoryMapNative_nativeCommit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_whispersystems_contactdiscovery_directory_DirectoryMapNative
 * Method:    nativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_whispersystems_contactdiscovery_directory_DirectoryMapNative_nativeSize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
